// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#r @"System.Core.dll"
#r @"System.dll"
#r @"System.Drawing.dll"
#r @"System.Numerics.dll"
#r @"..\..\..\packages\Aardvark.Base\lib\net45\Aardvark.Base.dll"
#r @"..\..\..\packages\Aardvark.Base.Essentials\lib\net45\Aardvark.Base.Essentials.dll"
#r @"..\..\..\packages\Aardvark.Base.FSharp\lib\net45\Aardvark.Base.FSharp.dll"
#r @"..\..\..\packages\Aardvark.Base.Incremental\lib\net45\Aardvark.Base.Incremental.dll"
#r @"..\..\..\packages\Aardvark.Base.FSharp\lib\net45\Aardvark.Base.TypeProviders.dll"
#r @"..\..\..\packages\DevILSharp\lib\net45\DevILSharp.dll"
#r @"..\..\..\packages\FSharp.Compiler.Service\lib\net45\FSharp.Compiler.Service.dll"
#r @"..\..\..\packages\RegexProvider\lib\net40\RegexProvider.dll"
#r @"..\..\..\packages\System.Collections.Immutable\lib\portable-net45+win8+wp8+wpa81\System.Collections.Immutable.dll"
#r @"..\..\..\packages\Rx-Core\lib\net45\System.Reactive.Core.dll"
#r @"..\..\..\packages\Rx-Interfaces\lib\net45\System.Reactive.Interfaces.dll"
#r @"..\..\..\packages\Rx-Linq\lib\net45\System.Reactive.Linq.dll"