// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#load @"load-references.fsx"
#load @"..\DefaultSemantic.fs"
      @"..\IndexedGeometry.fs"
      @"..\FrameStatistics.fs"
      @"..\DrawCallInfo.fs"
      @"..\Buffers.fs"
      @"..\Textures.fs"
      @"..\RenderJob.fs"
      @"..\GPUVendor.fs"
      @"..\Framebuffers.fs"
      @"..\Config.fs"
      @"..\Runtime.fs"
      @"..\RenderTask.fs"
